FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime
MAINTAINER dlcksgur3434@gmail.com
COPY requirements.txt .
RUN apt-get update -y && \
    apt-get -y upgrade && \
    apt-get install -y --no-install-recommends \
    python3 \
    python3-setuptools \
    python3-pip \
	python3-dev && \
    apt-get install -y git libssl-dev libusb-1.0-0-dev pkg-config libgtk-3-dev && \
    apt-get install -y libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev && \
    apt-get install gnupg -y && \
    apt-get install git -y && \
    git clone https://github.com/IntelRealSense/librealsense.git
COPY setup.sh ./librealsense/scripts
RUN cd ./librealsense && \
    ./scripts/setup.sh && \
    mkdir build && cd build && \
    cmake ../ -DBUILD_PYTHON_BINDINGS:bool=true && \
    make uninstall && make clean && make -j4 && make install && \
    export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.6/pyrealsense2 && \
    mkdir human_display_interaction && \
    apt-get update -y && \
    apt-get install -y python-pip python-dev build-essential && \
    apt-get install -y libgl1-mesa-glx && \
    apt-get -y install libusb-1.0-0-dev && \
    pip install -r requirements.txt